services:
  - type: web
    name: nambi-app
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nambi-db
          property: connectionString

databases:
  - name: nambi-db
    databaseName: nambi
    user: nambi_user